// import './global.css';

import { ReactNode } from 'react';

export const metadata = {
  title: 'Welcome to alt-zap web!',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
