# export AZ_PREFFIX="𝓐⚡"
export AZ_PREFFIX="${AZ_C_CYAN}[AltZap]${AZ_C_RESET}"

export AZ_PREFFIX_ECHO="$AZ_PREFFIX${AZ_C_CYAN}💬:${AZ_C_RESET}"
export AZ_PREFFIX_ERROR="$AZ_PREFFIX${AZ_C_CYAN}❌:${AZ_C_RESET}"
export AZ_PREFFIX_SUCCESS="$AZ_PREFFIX${AZ_C_CYAN}✅:${AZ_C_RESET}"
export AZ_PREFFIX_INFO="$AZ_PREFFIX${AZ_C_CYAN}ℹ️:${AZ_C_RESET}"
export AZ_PREFFIX_DEBUG="$AZ_PREFFIX${AZ_C_CYAN}🚧:${AZ_C_RESET}"

# export AZ_PREFFIX_ECHO="${AZ_C_CYAN}[AltZap]${AZ_C_RESET}"
# export AZ_PREFFIX_ERROR="$AZ_PREFFIX${AZ_C_CYAN}[AltZap:${AZ_C_DARK_RED}ERROR${AZ_C_CYAN}]${AZ_C_RESET}"
# export AZ_PREFFIX_DEBUG="${AZ_C_CYAN}[AltZap:${AZ_C_MAGENTA}DEBUG${AZ_C_CYAN}]${AZ_C_RESET}"
